name: Uploading an archive

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cloning RISC-V toolchain
        run: git clone --recursive https://github.com/riscv/riscv-gnu-toolchain
      - name: zip -r artifact_upload_test/riscv_gnu_pack.zip artifact_upload_test/riscv-gnu-toolchain
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: upload-archive
          path: artifact_upload_test/riscv_gnu_pack.zip
